# Generated by Django 5.0 on 2023-12-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('categori', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('reporter', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
    ]
